/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carros;

/**
 *
 * @author caans
 */
public class concesionario extends javax.swing.JFrame {

    /**
     * Creates new form concesionario
     */
    public concesionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Vehiculo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Dias = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Seguro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultado = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alquiler de Vehiculos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 390, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Alquilar un vehiculo");

        jLabel4.setText("Nombre del vehiculo:");

        jLabel5.setText("Dias de alquiler:");

        jLabel6.setText("Seguro todo riesgo:");

        jButton1.setBackground(new java.awt.Color(102, 255, 0));
        jButton1.setText("Hacer mi reserva ya");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Resultado.setColumns(20);
        Resultado.setRows(5);
        jScrollPane1.setViewportView(Resultado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Vehiculo)
                    .addComponent(Dias)
                    .addComponent(Seguro, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Seguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 360, 390));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carros/bmw.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 290, 120));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TWINGO $ 100000");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carros/megane.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 220, 130));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BMW $ 650000");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BMW $ 650000");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carros/mercedes.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 300, 110));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MEGANE $ 120000");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carros/twingo.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 250, 130));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("MERCEDES $ 700000");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carros/aveo.jpg"))); // NOI18N
        jLabel16.setText("CHEVROLET AVEO $ 150000");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\caans\\OneDrive\\Escritorio\\Adsi\\Java\\modulos\\carros\\fotos\\download.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String V,So,A="BMW",B="megane",C="mercedes",E="Twingo",F="chevrolet",decide="si";
double Desc,Rt,Des,D,R;

V=Vehiculo.getText();
D=Double.parseDouble(Dias.getText());
So=Seguro.getText();
if(D<=2){
    if(V.equalsIgnoreCase(A)){
        R=650000;
            if(So.equalsIgnoreCase(decide)){
                Desc=R*5;
                Desc=Desc/100;
                Rt=R+Desc;
                Resultado.setText("Por "+D+" no hay descuento, pero se suma el seguro todo riesgo del 5% lo cual seria un total de "+Rt);
                }
            else{
                Resultado.setText("Por "+D+" dias no hay descuento, entonces el valor a pagar es de"+R);
                }
	    }
		else if(V.equalsIgnoreCase(B)){
                    R=120000;
                      if(So.equalsIgnoreCase(decide)){
                                    Desc=R*5;
                                    Desc=Desc/100;
                                    Rt=R+Desc;
                                    Resultado.setText("Por "+D+" no hay descuento, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                    }
                                    else{
                                        Resultado.setText("Por "+D+" dias no hay descuento, entonces el valor a pagar es de"+R);
                                    }
			}
                                    else if(V.equalsIgnoreCase(C)){
                                        R=700000;
                                        if(So.equalsIgnoreCase(decide)){
                                            Desc=R*5;
                                            Desc=Desc/100;
                                            Rt=R+Desc;
                                            Resultado.setText("Por "+D+" no hay descuento, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                            }
                                            else{
                                                Resultado.setText("Por "+D+" dias no hay descuento, entonces el valor a pagar es de"+R);
                                            }
					}
                                         else if(V.equalsIgnoreCase(E)){
                                                
                                                R=100000;
                                                if(So.equalsIgnoreCase(decide)){
                                                    Desc=R*5;
                                                    Desc=Desc/100;
                                                    Rt=R+Desc;
                                                    Resultado.setText("Por "+D+" no hay descuento, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                                    }
                                                    else{
                                                        Resultado.setText("Por "+D+" dias no hay descuento, entonces el valor a pagar es de"+R);
                                                    }
                                                    }
                                                    else if(V.equalsIgnoreCase(F)){
                                                        
                                                        R=150000;
                                                        if(So.equalsIgnoreCase(decide)){
                                                            Desc=R*5;
                                                            Desc=Desc/100;
                                                            Rt=R+Desc;
                                                            Resultado.setText("Por "+D+" no hay descuento, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                                            }
                                                            else{
                                                                Resultado.setText("Por "+D+" dias no hay descuento, entonces el valor a pagar es de"+R);
                                                            }
                                                    }
                                                    else{ 
							Resultado.setText("Verifique que haya escrito bien el texto");
							} 

}
else if(D<=5){
    if(V.equalsIgnoreCase(A)){
        R=650000;
        Des=R*0.1;
        R=R-Des;
            if(So.equalsIgnoreCase(decide)){
                Desc=R*5;
                Desc=Desc/100;
                Rt=R+Desc;
                Resultado.setText("Por "+D+" dias hay descuento del 10%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                }
            else{
                Resultado.setText("Por "+D+" dias hay descuento de 10%, entonces el valor a pagar es de"+R);
                }
	    }
		else if(V.equalsIgnoreCase(B)){
                    R=120000;
                    Des=R*0.1;
                    R=R-Des;
                      if(So.equalsIgnoreCase(decide)){
                                    Desc=R*5;
                                    Desc=Desc/100;
                                    Rt=R+Desc;
                                    Resultado.setText("Por "+D+" dias hay descuento del 10%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                    }
                                    else{
                                        Resultado.setText("Por "+D+" dias hay descuento de 10%, entonces el valor a pagar es de"+R);
                                    }
			}
                                    else if(V.equalsIgnoreCase(C)){
                                        R=700000;
                            		Des=R*0.1;
                            		R=R-Des;
                                        if(So.equalsIgnoreCase(decide)){
                                            Desc=R*5;
                                            Desc=Desc/100;
                                            Rt=R+Desc;
                                            Resultado.setText("Por "+D+" dias no hay descuento, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                            }
                                            else{
                                                Resultado.setText("Por "+D+" dias hay descuento de 10%, entonces el valor a pagar es de"+R);
                                            }
					}
                                         else if(V.equalsIgnoreCase(E)){
                                                
                                                R=100000;
                            			Des=R*0.1;
                            			R=R-Des;
                                                if(So.equalsIgnoreCase(decide)){
                                                    Desc=R*5;
                                                    Desc=Desc/100;
                                                    Rt=R+Desc;
                                                    Resultado.setText("Por "+D+" dias hay descuento del 10%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                                    }
                                                    else{
                                                        Resultado.setText("Por "+D+" dias hay descuento de 10%, entonces el valor a pagar es de"+R);
                                                    }
                                                    }
                                                    else if(V.equalsIgnoreCase(F)){
                                                        
                                                        R=150000;
                            				Des=R*0.1;
                            				R=R-Des;
                                                        if(So.equalsIgnoreCase(decide)){
                                                            Desc=R*5;
                                                            Desc=Desc/100;
                                                            Rt=R+Desc;
                                                            Resultado.setText("Por "+D+" dias hay descuento del 10%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                                            }
                                                            else{
                                                                Resultado.setText("Por "+D+" dias hay descuento de 10%, entonces el valor a pagar es de"+R);
                                                            }
                                                    }
                                                    else{ 
							Resultado.setText("Verifique que haya escrito bien el texto");
							} 

}
else if(D<=10){
    if(V.equalsIgnoreCase(A)){
        R=650000;
        Des=R*0.15;
        R=R-Des;
            if(So.equalsIgnoreCase(decide)){
                Desc=R*5;
                Desc=Desc/100;
                Rt=R+Desc;
                Resultado.setText("Por "+D+" dias hay descuento del 15%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                }
            else{
                Resultado.setText("Por "+D+" dias hay descuento de 15%, entonces el valor a pagar es de"+R);
                }
	    }
		else if(V.equalsIgnoreCase(B)){
                    R=120000;
                    Des=R*0.15;
                    R=R-Des;
                      if(So.equalsIgnoreCase(decide)){
                                    Desc=R*5;
                                    Desc=Desc/100;
                                    Rt=R+Desc;
                                    Resultado.setText("Por "+D+" dias hay descuento del 15%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                    }
                                    else{
                                        Resultado.setText("Por "+D+" dias hay descuento de 15%, entonces el valor a pagar es de"+R);
                                    }
			}
                                    else if(V.equalsIgnoreCase(C)){
                                        R=700000;
                            		Des=R*0.15;
                            		R=R-Des;
                                        if(So.equalsIgnoreCase(decide)){
                                            Desc=R*5;
                                            Desc=Desc/100;
                                            Rt=R+Desc;
                                            Resultado.setText("Por "+D+" dias hay descuento del 15%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                            }
                                            else{
                                                Resultado.setText("Por "+D+" dias hay descuento de 15%, entonces el valor a pagar es de"+R);
                                            }
					}
                                         else if(V.equalsIgnoreCase(E)){
                                                
                                                R=100000;
                            			Des=R*0.15;
                            			R=R-Des;
                                                if(So.equalsIgnoreCase(decide)){
                                                    Desc=R*5;
                                                    Desc=Desc/100;
                                                    Rt=R+Desc;
                                                    Resultado.setText("Por "+D+" dias hay descuento del 15%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                                    }
                                                    else{
                                                        Resultado.setText("Por "+D+" dias hay descuento de 15%, entonces el valor a pagar es de"+R);
                                                    }
                                                    }
                                                    else if(V.equalsIgnoreCase(F)){
                                                        
                                                        R=150000;
                            				Des=R*0.15;
                            				R=R-Des;
                                                        if(So.equalsIgnoreCase(decide)){
                                                            Desc=R*5;
                                                            Desc=Desc/100;
                                                            Rt=R+Desc;
                                                            Resultado.setText("Por "+D+" dias hay descuento del 15%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                                            }
                                                            else{
                                                                Resultado.setText("Por "+D+" dias hay descuento de 15%, entonces el valor a pagar es de"+R);
                                                            }
                                                    }
                                                    else{ 
							Resultado.setText("Verifique que haya escrito bien el texto");
							} 
}
else if(D>10){
    if(V.equalsIgnoreCase(A)){
        R=650000;
        Des=R*0.2;
        R=R-Des;
            if(So.equalsIgnoreCase(decide)){
                Desc=R*5;
                Desc=Desc/100;
                Rt=R+Desc;
                Resultado.setText("Por "+D+" dias hay descuento del 20%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                }
            else{
                Resultado.setText("Por "+D+" dias hay descuento de 20%, entonces el valor a pagar es de"+R);
                }
	    }
		else if(V.equalsIgnoreCase(B)){
                    R=120000;
                    Des=R*0.2;
                    R=R-Des;
                      if(So.equalsIgnoreCase(decide)){
                                    Desc=R*5;
                                    Desc=Desc/100;
                                    Rt=R+Desc;
                                    Resultado.setText("Por "+D+" dias hay descuento del 20%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                    }
                                    else{
                                        Resultado.setText("Por "+D+" dias hay descuento de 20%, entonces el valor a pagar es de"+R);
                                    }
			}
                                    else if(V.equalsIgnoreCase(C)){
                                        R=700000;
                            		Des=R*0.2;
                            		R=R-Des;
                                        if(So.equalsIgnoreCase(decide)){
                                            Desc=R*5;
                                            Desc=Desc/100;
                                            Rt=R+Desc;
                                            Resultado.setText("Por "+D+" dias hay descuento del 20%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                            }
                                            else{
                                                Resultado.setText("Por "+D+" dias hay descuento de 20%, entonces el valor a pagar es de"+R);
                                            }
					}
                                         else if(V.equalsIgnoreCase(E)){
                                                
                                                R=100000;
                            			Des=R*0.2;
                            			R=R-Des;
                                                if(So.equalsIgnoreCase(decide)){
                                                    Desc=R*5;
                                                    Desc=Desc/100;
                                                    Rt=R+Desc;
                                                    Resultado.setText("Por "+D+" dias hay descuento del 20%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                                    }
                                                    else{
                                                        Resultado.setText("Por "+D+" dias hay descuento de 20%, entonces el valor a pagar es de"+R);
                                                    }
                                                    }
                                                    else if(V.equalsIgnoreCase(F)){
                                                        
                                                        R=150000;
                            				Des=R*0.2;
                            				R=R-Des;
                                                        if(So.equalsIgnoreCase(decide)){
                                                            Desc=R*5;
                                                            Desc=Desc/100;
                                                            Rt=R+Desc;
                                                            Resultado.setText("Por "+D+" dias hay descuento del 20%, pero se suma el seguro todo riesgo del 5% lo cual seria un total de"+Rt);
                                                            }
                                                            else{
                                                                Resultado.setText("Por "+D+" dias hay descuento de 20%, entonces el valor a pagar es de"+R);
                                                            }
                                                    }
                                                    else{ 
							Resultado.setText("Verifique que haya escrito bien el texto");
							} 
}
else{
	Resultado.setText("El dia digitado no es valido mi rey");
}
    }//GEN-LAST:event_jButton1ActionPerformed

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(concesionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(concesionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(concesionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(concesionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new concesionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dias;
    private javax.swing.JTextArea Resultado;
    private javax.swing.JTextField Seguro;
    private javax.swing.JTextField Vehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
